# Generated by Django 2.2.6 on 2019-10-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('HC', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='playerimages')),
                ('jacket', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, null=True)),
                ('highfinish', models.IntegerField(blank=True, null=True)),
                ('tournum', models.IntegerField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
            ],
            options={
                'ordering': ['-total'],
            },
        ),
    ]
